# Generated by Django 5.2.5 on 2025-08-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre de la oficina'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='nombre_corto',
            field=models.SlugField(help_text='Identificador único corto para la oficina(ej:IAS, ADM, ETC.)', max_length=10, unique=True, verbose_name='ID corto'),
        ),
    ]
