# Generated by Django 5.2.5 on 2025-08-25 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0002_alter_oficina_nombre_alter_oficina_nombre_corto'),
        ('persona', '0003_alter_persona_oficina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='oficina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='oficina.oficina'),
        ),
    ]
